#!/usr/bin/env python3
#
#This is my code which includes a function that will check if i have "Monday" in my calender and prints it in Uppercase
#
def find_monday(mycalender1):
    mycalendar1 =  """Day           Time           Subject
                    Monday    9:10 AM - 10:15 AM      LA
                              10:35 AM - 11:40 AM     SS
                              12:10 PM - 1:15 PM      S
                    Friday    9:10 AM - 10:15 AM     Math
                              10:35 AM - 11:40 AM  Exploratory Wheel
                              12:10 PM - 1:15 PM      PF"""
#This is my calender for school

If "Monday" in mycalendar1:
       print "Monday is written in this schedule."
   else:
       print "Monday is not written in this schedule."
       
#This is my Function     
     return
def main():
    print find_monday()
    print mycalendar.upper()
#This is where i will print my schedule in Uppercase
